2025-01-05 16:09:40,463 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2025-01-05 16:10:40,466 - httpx - INFO - HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-05 16:10:54,303 - httpx - INFO - HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-05 16:11:15,573 - httpx - INFO - HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-05 16:11:15,574 - AI_Recruiter - ERROR - Error processing resume: name 'analysis_results_detailed' is not defined
2025-01-05 16:11:15,581 - AI_Recruiter - ERROR - Processing error: name 'analysis_results_detailed' is not defined
Traceback (most recent call last):
  File "C:\Users\Asiri Jayawardena\Desktop\OLLAMA\rag-recuiter\app.py", line 128, in main
    result = asyncio.run(process_resume(file_path))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\global\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\global\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\envs\global\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Asiri Jayawardena\Desktop\OLLAMA\rag-recuiter\app.py", line 58, in process_resume
    return await orchestrator.process_application(resume_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asiri Jayawardena\Desktop\OLLAMA\rag-recuiter\agents\orchestrator_agent.py", line 58, in process_application
    {"analysis_results": analysis_results,"detailed_analysis":analysis_results_detailed,"current_stage": "matching"}
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'analysis_results_detailed' is not defined
